import { REACT_APP_BACKEND_GETALLSUBASTAS,
  REACT_APP_BACKEND_LOGIN,
  REACT_APP_BACKEND_GETPERSONA,
  REACT_APP_BACKEND_GENERATEPASSWORD,
  REACT_APP_BACKEND_GETCURRENTUSER} from '@env';
 
export default {
  API_URL:"https://73efa93980f5.ngrok.io",
  REACT_APP_BACKEND_GETALLSUBASTAS,
  REACT_APP_BACKEND_LOGIN,
  REACT_APP_BACKEND_GETPERSONA,
  REACT_APP_BACKEND_GENERATEPASSWORD,
  REACT_APP_BACKEND_GETCURRENTUSER
};