import { REACT_APP_BACKEND_GETALLSUBASTAS,
  REACT_APP_BACKEND_ADDPERSONA,
  REACT_APP_BACKEND_ADDUSER,
  REACT_APP_BACKEND_LOGIN,
  REACT_APP_BACKEND_GETPERSONA,
  REACT_APP_BACKEND_ADDCLIENTE,
  REACT_APP_BACKEND_GETALLCATEGORIASUBASTAS,
  REACT_APP_BACKEND_ADDMEDIOPAGO,
  REACT_APP_BACKEND_ADDPRODUCTO,
  REACT_APP_BACKEND_ADDFOTO,
  REACT_APP_BACKEND_GETPRODUCTOS,
  REACT_APP_BACKEND_GETALLPRODUCTOS,
  REACT_APP_BACKEND_GENERATEPASSWORD,
  REACT_APP_BACKEND_GETCURRENTUSER
} from '@env';
 
export default {
  API_URL:"https://f382f0b4ef12.ngrok.io",
  REACT_APP_BACKEND_GETALLSUBASTAS,
  REACT_APP_BACKEND_ADDPERSONA,
  REACT_APP_BACKEND_ADDUSER,
  REACT_APP_BACKEND_LOGIN,
  REACT_APP_BACKEND_GETPERSONA,
  REACT_APP_BACKEND_ADDCLIENTE,
  REACT_APP_BACKEND_GETALLCATEGORIASUBASTAS,
  REACT_APP_BACKEND_ADDMEDIOPAGO,
  REACT_APP_BACKEND_ADDPRODUCTO,
  REACT_APP_BACKEND_ADDFOTO,
  REACT_APP_BACKEND_GETPRODUCTOS,
  REACT_APP_BACKEND_GETALLPRODUCTOS,
  REACT_APP_BACKEND_GENERATEPASSWORD,
  REACT_APP_BACKEND_GETCURRENTUSER
};