import { REACT_APP_BACKEND_GETALLSUBASTAS,
  REACT_APP_BACKEND_ADDPERSONA,
  REACT_APP_BACKEND_ADDUSER,
  REACT_APP_BACKEND_LOGIN,
  REACT_APP_BACKEND_GETPERSONA,
  REACT_APP_BACKEND_ADDCLIENTE,
  REACT_APP_BACKEND_GETALLCATEGORIASUBASTAS,
  REACT_APP_BACKEND_ADDMEDIOPAGO,
  REACT_APP_BACKEND_ADDPRODUCTO,
  REACT_APP_BACKEND_GENERATEPASSWORD,
  REACT_APP_BACKEND_GETCURRENTUSER
} from '@env';
 
export default {
  API_URL:"https://7fc81b55699a.ngrok.io",
  REACT_APP_BACKEND_GETALLSUBASTAS,
  REACT_APP_BACKEND_ADDPERSONA,
  REACT_APP_BACKEND_ADDUSER,
  REACT_APP_BACKEND_LOGIN,
  REACT_APP_BACKEND_GETPERSONA,
  REACT_APP_BACKEND_ADDCLIENTE,
  REACT_APP_BACKEND_GETALLCATEGORIASUBASTAS,
  REACT_APP_BACKEND_ADDMEDIOPAGO,
  REACT_APP_BACKEND_ADDPRODUCTO,
  REACT_APP_BACKEND_GENERATEPASSWORD,
  REACT_APP_BACKEND_GETCURRENTUSER
};